//
//  PlaybackDiagnosticsView.swift
//  BurstStream
//

import SwiftUI

/// Expandable panel for studying metrics generated by AVPlayer during HLS.
/// It receives a simple model and does not know AVPlayerItemAccessLog directly.
struct PlaybackDiagnosticsView: View {
    let metrics: PlaybackMetrics

    var body: some View {
        DisclosureGroup {
            VStack(alignment: .leading, spacing: 10) {
                if metrics.accessLogEntries == 0 {
                    Label("Waiting for access log data", systemImage: "clock")
                        .font(.footnote)
                        .foregroundStyle(.secondary)
                }

                // presentationSize may retain its initial value after an HLS
                // variant switch, so it is not labeled as the current quality.
                metricRow("Presentation size", value: resolutionText)
                metricRow("Playback type", value: metrics.playbackType ?? "—")
                metricRow("Observed throughput", value: formatBitrate(metrics.observedBitrate))
                metricRow("Required bitrate", value: formatBitrate(metrics.indicatedBitrate))
                metricRow("Switch bitrate", value: formatBitrate(metrics.switchBitrate))
                metricRow("Average video bitrate", value: formatBitrate(metrics.averageVideoBitrate))
                metricRow("Media requests", value: formatInteger(metrics.mediaRequests))
                metricRow("Downloaded media", value: formatDuration(metrics.downloadedDuration))
                metricRow("Duration watched", value: formatDuration(metrics.durationWatched))
                metricRow("Transferred", value: formatBytes(metrics.bytesTransferred))
                metricRow("Playback stalls", value: formatInteger(metrics.stalls))
                metricRow("Dropped frames", value: formatInteger(metrics.droppedVideoFrames))
                metricRow("Startup time", value: formatDuration(metrics.startupTime))
                metricRow("Access log entries", value: "\(metrics.accessLogEntries)")
                metricRow("Error log entries", value: "\(metrics.errorLogEntries)")

                if let serverAddress = metrics.serverAddress {
                    diagnosticText("Server", value: serverAddress)
                }

                if let uri = metrics.uri {
                    diagnosticText("Current resource", value: uri)
                }

                if let error = metrics.latestError {
                    Divider()

                    VStack(alignment: .leading, spacing: 4) {
                        Label("Latest logged error", systemImage: "exclamationmark.triangle")
                            .font(.subheadline.weight(.semibold))
                            .foregroundStyle(.red)

                        Text("\(error.domain) · status \(error.statusCode)")
                            .font(.caption.monospaced())

                        if let comment = error.comment {
                            Text(comment)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                    }
                }
            }
            .padding(.top, 12)
        } label: {
            Label("Streaming diagnostics", systemImage: "waveform.path.ecg.rectangle")
                .font(.headline)
        }
        .padding()
        .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 14))
    }

    private var resolutionText: String {
        guard let width = metrics.videoWidth,
              let height = metrics.videoHeight else {
            return "—"
        }

        return "\(width) × \(height)"
    }

    private func metricRow(_ label: String, value: String) -> some View {
        LabeledContent(label, value: value)
            .font(.footnote)
    }

    private func diagnosticText(_ label: String, value: String) -> some View {
        VStack(alignment: .leading, spacing: 3) {
            Text(label)
                .font(.caption.weight(.semibold))

            Text(value)
                .font(.caption.monospaced())
                .foregroundStyle(.secondary)
                .textSelection(.enabled)
        }
    }

    private func formatBitrate(_ bitsPerSecond: Double?) -> String {
        guard let bitsPerSecond else { return "—" }

        if bitsPerSecond >= 1_000_000 {
            return String(format: "%.2f Mbps", bitsPerSecond / 1_000_000)
        }

        return String(format: "%.0f Kbps", bitsPerSecond / 1_000)
    }

    private func formatBytes(_ bytes: Int64?) -> String {
        guard let bytes else { return "—" }
        return ByteCountFormatter.string(fromByteCount: bytes, countStyle: .file)
    }

    private func formatDuration(_ seconds: TimeInterval?) -> String {
        guard let seconds else { return "—" }
        return String(format: "%.2f s", seconds)
    }

    private func formatInteger(_ value: Int?) -> String {
        value.map(String.init) ?? "—"
    }
}
